### ISSUE TITLE
Edge file not found

### ISSUE THREAD

**Issue by govind17** [sjj0403/GSCS#3]
Can you please  state where or how to get the Edge file?

I  am getting error due to this line
edge_file = open(config.edge_dir+adj_path,'rb')

Corresponding, step: https://github.com/sjj0403/GSCS/blob/d2ab924de23ee330f0774d3c241f40533216e886/gscs/train.py#L184

**Comment by sjj0403** [comment]
Edge file can be obtained by the function&nbsp;get_adjacent in file&nbsp;strudata.py. But as it is too big, you can split it into several small files.
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Mon, May 23, 2022 08:48 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[sjj0403/GSCS] Edge file not found (Issue #3)

&nbsp;



 
Can you please where or how to get the Edge file?
 
I  am getting error due to this line
 edge_file = open(config.edge_dir+adj_path,'rb')
 
Corresponding, step: https://github.com/sjj0403/GSCS/blob/d2ab924de23ee330f0774d3c241f40533216e886/gscs/train.py#L184

**Comment by sjj0403** [comment]
This may not work.
The train_code_path corresponds to&nbsp;code.original_subtoken, train_type_path corresponds to AST's node sequence (which can be obtained by the function&nbsp;get_adjacent2 in file&nbsp;strudata.py) and train_nl_path corresponds to javadoc.original. Edge file (which can be obtained by the function&nbsp;get_adjacent in file&nbsp;strudata.py) is also used in our approach.
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Mon, May 23, 2022 08:48 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[sjj0403/GSCS] Edge file not found (Issue #3)

&nbsp;



 
Can you please where or how to get the Edge file?
 
I  am getting error due to this line
 edge_file = open(config.edge_dir+adj_path,'rb')
 
Corresponding, step: https://github.com/sjj0403/GSCS/blob/d2ab924de23ee330f0774d3c241f40533216e886/gscs/train.py#L184
